### ISSUE TITLE
String#to_edn can include Ruby escape chars not valid in EDN

### ISSUE THREAD

**Issue by rcrogers** [relevance/edn-ruby#34]
```
2.2.0 :022 > puts 'foo #{ bar'.to_edn
"foo \#{ bar"
```

If such a string is used in a Datomic query, it causes an error:
```
Caused by: java.lang.RuntimeException: Unsupported escape character: \#
	at clojure.lang.Util.runtimeException(Util.java:221) ~[clojure-1.6.0.jar:na]
	at clojure.lang.EdnReader$StringReader.invoke(EdnReader.java:454) ~[clojure-1.6.0.jar:na]
```

This seems to result from the use of String#inspect to implement String#to_edn.

**Comment by russolsen** [comment]
Fixed.
