### ISSUE TITLE
error with windows line endings

### ISSUE THREAD

**Issue by trevor** [relevance/edn-ruby#37]
A file with the content:

```
{
}
```

Formatted with CRLF endings:

```
% file a.edn
a.edn: ASCII text, with CRLF line terminators

% hexdump a.edn
0000000 7b 0d 0a 7d 0d 0a
```

Will throw the error:

```ruby
 String (RuntimeError)ms/2.3.0/gems/edn-1.1.0/lib/edn/ruby_edn_parser.rb:27:in `unknown': Don't know what to do with
	from /usr/local/lib/ruby/gems/2.3.0/gems/edn-1.1.0/lib/edn/ruby_edn_parser.rb:148:in `call_reader'
	from /usr/local/lib/ruby/gems/2.3.0/gems/edn-1.1.0/lib/edn/ruby_edn_parser.rb:157:in `read_basic'
	from /usr/local/lib/ruby/gems/2.3.0/gems/edn-1.1.0/lib/edn/ruby_edn_parser.rb:14:in `read'
	from /usr/local/lib/ruby/gems/2.3.0/gems/edn-1.1.0/lib/edn/ruby_edn_parser.rb:259:in `read_collection'
	from /usr/local/lib/ruby/gems/2.3.0/gems/edn-1.1.0/lib/edn/ruby_edn_parser.rb:247:in `read_map'
	from /usr/local/lib/ruby/gems/2.3.0/gems/edn-1.1.0/lib/edn/ruby_edn_parser.rb:148:in `call_reader'
	from /usr/local/lib/ruby/gems/2.3.0/gems/edn-1.1.0/lib/edn/ruby_edn_parser.rb:157:in `read_basic'
	from /usr/local/lib/ruby/gems/2.3.0/gems/edn-1.1.0/lib/edn/ruby_edn_parser.rb:14:in `read'
	from /usr/local/lib/ruby/gems/2.3.0/gems/edn-1.1.0/lib/edn/reader.rb:9:in `read'
	from /usr/local/lib/ruby/gems/2.3.0/gems/edn-1.1.0/lib/edn.rb:16:in `read'
```

**Comment by russolsen** [comment]
Fixed in edn-1.1.1
