### ISSUE TITLE
warning: constant ::Bignum is deprecated

### ISSUE THREAD

**Issue by trevor** [relevance/edn-ruby#39]
```
% ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

irb(main):001:0> require 'edn'
/usr/local/lib/ruby/gems/2.4.0/gems/edn-1.1.1/lib/edn/core_ext.rb:97: warning: constant ::Bignum is deprecated
```

**Comment by trevor** [comment]
`Bignum` has been removed in Ruby 3.2, this now causes an error instead of a warning.

Ref: https://rubyreferences.github.io/rubychanges/3.2.html#removals

```
% ruby --version
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [arm64-darwin22]

irb(main):001:0> require 'edn'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/edn-1.1.1/lib/edn/core_ext.rb:97:in `<top (required)>': uninitialized constant Bignum (NameError)

Bignum.send(:include, EDN::CoreExt::Bignum)
^^^^^^
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/edn-1.1.1/lib/edn.rb:4:in `<top (required)>'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:162:in `require'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:162:in `rescue in require'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:152:in `require'
	from (irb):1:in `<main>'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
	from /opt/homebrew/opt/ruby/bin/irb:25:in `load'
	from /opt/homebrew/opt/ruby/bin/irb:25:in `<main>'
<internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require': cannot load such file -- edn (LoadError)
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
	from (irb):1:in `<main>'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
	from /opt/homebrew/opt/ruby/bin/irb:25:in `load'
	from /opt/homebrew/opt/ruby/bin/irb:25:in `<main>'
```

**Comment by jgomo3** [comment]
This error would be fixed with the PR https://github.com/relevance/edn-ruby/pull/42

In particular with this change https://github.com/relevance/edn-ruby/pull/42/files#diff-61ff3de53f862ec463867dc7587198545543f65a5c1103ded35d660002f08626

That change simply removes the extension to the `Bignum` module, which doesn't exist anymore.

**Comment by trevor** [comment]
@jgomo3 From all appearances the @relevance organization is no longer a going concern.

Have a look at https://github.com/edn2023/edn2023 and https://github.com/edporras/edn_turbo for EDN support in Ruby.
